// Generated by CIRCT firtool-1.62.1
module MatrixAlu(
  input  [7:0]  io_a,
                io_b,
  input  [31:0] io_c,
  output [31:0] io_madd,
                io_msub,
                io_hmul,
                io_mac
);

  wire [15:0] prod16 = {8'h0, io_a} * {8'h0, io_b};
  wire [31:0] _GEN = {24'h0, io_a};
  wire [31:0] _GEN_0 = {24'h0, io_b};
  assign io_madd = _GEN + _GEN_0;
  assign io_msub = _GEN - _GEN_0;
  assign io_hmul = {16'h0, prod16};
  assign io_mac = io_c + {16'h0, prod16};
endmodule

module MatrixCore(
  input         clock,
                reset,
  input  [3:0]  io_opcode,
  input  [1:0]  io_row,
                io_col,
  input  [7:0]  io_data,
  input         io_start,
  output [31:0] io_rdata,
  output        io_done,
                io_busy
);

  wire [31:0] _alu_io_madd;
  wire [31:0] _alu_io_msub;
  wire [31:0] _alu_io_hmul;
  wire [31:0] _alu_io_mac;
  reg  [7:0]  a_0_0;
  reg  [7:0]  a_0_1;
  reg  [7:0]  a_0_2;
  reg  [7:0]  a_0_3;
  reg  [7:0]  a_1_0;
  reg  [7:0]  a_1_1;
  reg  [7:0]  a_1_2;
  reg  [7:0]  a_1_3;
  reg  [7:0]  a_2_0;
  reg  [7:0]  a_2_1;
  reg  [7:0]  a_2_2;
  reg  [7:0]  a_2_3;
  reg  [7:0]  a_3_0;
  reg  [7:0]  a_3_1;
  reg  [7:0]  a_3_2;
  reg  [7:0]  a_3_3;
  reg  [7:0]  b_0_0;
  reg  [7:0]  b_0_1;
  reg  [7:0]  b_0_2;
  reg  [7:0]  b_0_3;
  reg  [7:0]  b_1_0;
  reg  [7:0]  b_1_1;
  reg  [7:0]  b_1_2;
  reg  [7:0]  b_1_3;
  reg  [7:0]  b_2_0;
  reg  [7:0]  b_2_1;
  reg  [7:0]  b_2_2;
  reg  [7:0]  b_2_3;
  reg  [7:0]  b_3_0;
  reg  [7:0]  b_3_1;
  reg  [7:0]  b_3_2;
  reg  [7:0]  b_3_3;
  reg  [31:0] c_0_0;
  reg  [31:0] c_0_1;
  reg  [31:0] c_0_2;
  reg  [31:0] c_0_3;
  reg  [31:0] c_1_0;
  reg  [31:0] c_1_1;
  reg  [31:0] c_1_2;
  reg  [31:0] c_1_3;
  reg  [31:0] c_2_0;
  reg  [31:0] c_2_1;
  reg  [31:0] c_2_2;
  reg  [31:0] c_2_3;
  reg  [31:0] c_3_0;
  reg  [31:0] c_3_1;
  reg  [31:0] c_3_2;
  reg  [31:0] c_3_3;
  reg         busy;
  reg         done;
  reg  [31:0] rdata;
  reg  [3:0]  op;
  reg  [1:0]  i;
  reg  [1:0]  j;
  reg  [1:0]  k;
  reg  [1:0]  latchedRow;
  reg  [1:0]  latchedCol;
  reg  [7:0]  latchedData;
  wire        _alu_io_b_T = op == 4'h7;
  wire        _isElemWalk_T_5 = op == 4'h8;
  reg  [7:0]  casez_tmp;
  always_comb begin
    casez (j)
      2'b00:
        casez_tmp = a_0_0;
      2'b01:
        casez_tmp = a_1_0;
      2'b10:
        casez_tmp = a_2_0;
      default:
        casez_tmp = a_3_0;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_0;
  always_comb begin
    casez (j)
      2'b00:
        casez_tmp_0 = a_0_1;
      2'b01:
        casez_tmp_0 = a_1_1;
      2'b10:
        casez_tmp_0 = a_2_1;
      default:
        casez_tmp_0 = a_3_1;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_1;
  always_comb begin
    casez (j)
      2'b00:
        casez_tmp_1 = a_0_2;
      2'b01:
        casez_tmp_1 = a_1_2;
      2'b10:
        casez_tmp_1 = a_2_2;
      default:
        casez_tmp_1 = a_3_2;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_2;
  always_comb begin
    casez (j)
      2'b00:
        casez_tmp_2 = a_0_3;
      2'b01:
        casez_tmp_2 = a_1_3;
      2'b10:
        casez_tmp_2 = a_2_3;
      default:
        casez_tmp_2 = a_3_3;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_3;
  always_comb begin
    casez (i)
      2'b00:
        casez_tmp_3 = casez_tmp;
      2'b01:
        casez_tmp_3 = casez_tmp_0;
      2'b10:
        casez_tmp_3 = casez_tmp_1;
      default:
        casez_tmp_3 = casez_tmp_2;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_4;
  always_comb begin
    casez (i)
      2'b00:
        casez_tmp_4 = a_0_0;
      2'b01:
        casez_tmp_4 = a_1_0;
      2'b10:
        casez_tmp_4 = a_2_0;
      default:
        casez_tmp_4 = a_3_0;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_5;
  always_comb begin
    casez (i)
      2'b00:
        casez_tmp_5 = a_0_1;
      2'b01:
        casez_tmp_5 = a_1_1;
      2'b10:
        casez_tmp_5 = a_2_1;
      default:
        casez_tmp_5 = a_3_1;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_6;
  always_comb begin
    casez (i)
      2'b00:
        casez_tmp_6 = a_0_2;
      2'b01:
        casez_tmp_6 = a_1_2;
      2'b10:
        casez_tmp_6 = a_2_2;
      default:
        casez_tmp_6 = a_3_2;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_7;
  always_comb begin
    casez (i)
      2'b00:
        casez_tmp_7 = a_0_3;
      2'b01:
        casez_tmp_7 = a_1_3;
      2'b10:
        casez_tmp_7 = a_2_3;
      default:
        casez_tmp_7 = a_3_3;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_8;
  always_comb begin
    casez (j)
      2'b00:
        casez_tmp_8 = casez_tmp_4;
      2'b01:
        casez_tmp_8 = casez_tmp_5;
      2'b10:
        casez_tmp_8 = casez_tmp_6;
      default:
        casez_tmp_8 = casez_tmp_7;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_9;
  always_comb begin
    casez (k)
      2'b00:
        casez_tmp_9 = casez_tmp_4;
      2'b01:
        casez_tmp_9 = casez_tmp_5;
      2'b10:
        casez_tmp_9 = casez_tmp_6;
      default:
        casez_tmp_9 = casez_tmp_7;
    endcase
  end // always_comb
  wire [7:0]  _alu_io_a_T_3 =
    _alu_io_b_T ? casez_tmp_9 : _isElemWalk_T_5 ? casez_tmp_3 : casez_tmp_8;
  reg  [7:0]  casez_tmp_10;
  always_comb begin
    casez (k)
      2'b00:
        casez_tmp_10 = b_0_0;
      2'b01:
        casez_tmp_10 = b_1_0;
      2'b10:
        casez_tmp_10 = b_2_0;
      default:
        casez_tmp_10 = b_3_0;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_11;
  always_comb begin
    casez (k)
      2'b00:
        casez_tmp_11 = b_0_1;
      2'b01:
        casez_tmp_11 = b_1_1;
      2'b10:
        casez_tmp_11 = b_2_1;
      default:
        casez_tmp_11 = b_3_1;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_12;
  always_comb begin
    casez (k)
      2'b00:
        casez_tmp_12 = b_0_2;
      2'b01:
        casez_tmp_12 = b_1_2;
      2'b10:
        casez_tmp_12 = b_2_2;
      default:
        casez_tmp_12 = b_3_2;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_13;
  always_comb begin
    casez (k)
      2'b00:
        casez_tmp_13 = b_0_3;
      2'b01:
        casez_tmp_13 = b_1_3;
      2'b10:
        casez_tmp_13 = b_2_3;
      default:
        casez_tmp_13 = b_3_3;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_14;
  always_comb begin
    casez (j)
      2'b00:
        casez_tmp_14 = casez_tmp_10;
      2'b01:
        casez_tmp_14 = casez_tmp_11;
      2'b10:
        casez_tmp_14 = casez_tmp_12;
      default:
        casez_tmp_14 = casez_tmp_13;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_15;
  always_comb begin
    casez (i)
      2'b00:
        casez_tmp_15 = b_0_0;
      2'b01:
        casez_tmp_15 = b_1_0;
      2'b10:
        casez_tmp_15 = b_2_0;
      default:
        casez_tmp_15 = b_3_0;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_16;
  always_comb begin
    casez (i)
      2'b00:
        casez_tmp_16 = b_0_1;
      2'b01:
        casez_tmp_16 = b_1_1;
      2'b10:
        casez_tmp_16 = b_2_1;
      default:
        casez_tmp_16 = b_3_1;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_17;
  always_comb begin
    casez (i)
      2'b00:
        casez_tmp_17 = b_0_2;
      2'b01:
        casez_tmp_17 = b_1_2;
      2'b10:
        casez_tmp_17 = b_2_2;
      default:
        casez_tmp_17 = b_3_2;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_18;
  always_comb begin
    casez (i)
      2'b00:
        casez_tmp_18 = b_0_3;
      2'b01:
        casez_tmp_18 = b_1_3;
      2'b10:
        casez_tmp_18 = b_2_3;
      default:
        casez_tmp_18 = b_3_3;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_19;
  always_comb begin
    casez (j)
      2'b00:
        casez_tmp_19 = casez_tmp_15;
      2'b01:
        casez_tmp_19 = casez_tmp_16;
      2'b10:
        casez_tmp_19 = casez_tmp_17;
      default:
        casez_tmp_19 = casez_tmp_18;
    endcase
  end // always_comb
  reg  [31:0] casez_tmp_20;
  always_comb begin
    casez (i)
      2'b00:
        casez_tmp_20 = c_0_0;
      2'b01:
        casez_tmp_20 = c_1_0;
      2'b10:
        casez_tmp_20 = c_2_0;
      default:
        casez_tmp_20 = c_3_0;
    endcase
  end // always_comb
  reg  [31:0] casez_tmp_21;
  always_comb begin
    casez (i)
      2'b00:
        casez_tmp_21 = c_0_1;
      2'b01:
        casez_tmp_21 = c_1_1;
      2'b10:
        casez_tmp_21 = c_2_1;
      default:
        casez_tmp_21 = c_3_1;
    endcase
  end // always_comb
  reg  [31:0] casez_tmp_22;
  always_comb begin
    casez (i)
      2'b00:
        casez_tmp_22 = c_0_2;
      2'b01:
        casez_tmp_22 = c_1_2;
      2'b10:
        casez_tmp_22 = c_2_2;
      default:
        casez_tmp_22 = c_3_2;
    endcase
  end // always_comb
  reg  [31:0] casez_tmp_23;
  always_comb begin
    casez (i)
      2'b00:
        casez_tmp_23 = c_0_3;
      2'b01:
        casez_tmp_23 = c_1_3;
      2'b10:
        casez_tmp_23 = c_2_3;
      default:
        casez_tmp_23 = c_3_3;
    endcase
  end // always_comb
  reg  [31:0] casez_tmp_24;
  always_comb begin
    casez (j)
      2'b00:
        casez_tmp_24 = casez_tmp_20;
      2'b01:
        casez_tmp_24 = casez_tmp_21;
      2'b10:
        casez_tmp_24 = casez_tmp_22;
      default:
        casez_tmp_24 = casez_tmp_23;
    endcase
  end // always_comb
  reg  [31:0] casez_tmp_25;
  always_comb begin
    casez (latchedRow)
      2'b00:
        casez_tmp_25 = c_0_0;
      2'b01:
        casez_tmp_25 = c_1_0;
      2'b10:
        casez_tmp_25 = c_2_0;
      default:
        casez_tmp_25 = c_3_0;
    endcase
  end // always_comb
  reg  [31:0] casez_tmp_26;
  always_comb begin
    casez (latchedRow)
      2'b00:
        casez_tmp_26 = c_0_1;
      2'b01:
        casez_tmp_26 = c_1_1;
      2'b10:
        casez_tmp_26 = c_2_1;
      default:
        casez_tmp_26 = c_3_1;
    endcase
  end // always_comb
  reg  [31:0] casez_tmp_27;
  always_comb begin
    casez (latchedRow)
      2'b00:
        casez_tmp_27 = c_0_2;
      2'b01:
        casez_tmp_27 = c_1_2;
      2'b10:
        casez_tmp_27 = c_2_2;
      default:
        casez_tmp_27 = c_3_2;
    endcase
  end // always_comb
  reg  [31:0] casez_tmp_28;
  always_comb begin
    casez (latchedRow)
      2'b00:
        casez_tmp_28 = c_0_3;
      2'b01:
        casez_tmp_28 = c_1_3;
      2'b10:
        casez_tmp_28 = c_2_3;
      default:
        casez_tmp_28 = c_3_3;
    endcase
  end // always_comb
  reg  [31:0] casez_tmp_29;
  always_comb begin
    casez (latchedCol)
      2'b00:
        casez_tmp_29 = casez_tmp_25;
      2'b01:
        casez_tmp_29 = casez_tmp_26;
      2'b10:
        casez_tmp_29 = casez_tmp_27;
      default:
        casez_tmp_29 = casez_tmp_28;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_30;
  always_comb begin
    casez (latchedRow)
      2'b00:
        casez_tmp_30 = a_0_0;
      2'b01:
        casez_tmp_30 = a_1_0;
      2'b10:
        casez_tmp_30 = a_2_0;
      default:
        casez_tmp_30 = a_3_0;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_31;
  always_comb begin
    casez (latchedRow)
      2'b00:
        casez_tmp_31 = a_0_1;
      2'b01:
        casez_tmp_31 = a_1_1;
      2'b10:
        casez_tmp_31 = a_2_1;
      default:
        casez_tmp_31 = a_3_1;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_32;
  always_comb begin
    casez (latchedRow)
      2'b00:
        casez_tmp_32 = a_0_2;
      2'b01:
        casez_tmp_32 = a_1_2;
      2'b10:
        casez_tmp_32 = a_2_2;
      default:
        casez_tmp_32 = a_3_2;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_33;
  always_comb begin
    casez (latchedRow)
      2'b00:
        casez_tmp_33 = a_0_3;
      2'b01:
        casez_tmp_33 = a_1_3;
      2'b10:
        casez_tmp_33 = a_2_3;
      default:
        casez_tmp_33 = a_3_3;
    endcase
  end // always_comb
  reg  [7:0]  casez_tmp_34;
  always_comb begin
    casez (latchedCol)
      2'b00:
        casez_tmp_34 = casez_tmp_30;
      2'b01:
        casez_tmp_34 = casez_tmp_31;
      2'b10:
        casez_tmp_34 = casez_tmp_32;
      default:
        casez_tmp_34 = casez_tmp_33;
    endcase
  end // always_comb
  wire        _elemC_T = op == 4'h4;
  wire        _elemC_T_2 = op == 4'h5;
  wire        _elemC_T_4 = op == 4'h6;
  wire        _elemC_T_6 = op == 4'h8;
  wire [31:0] _GEN = {24'h0, _alu_io_a_T_3};
  wire [31:0] matmulC = k == 2'h0 ? _alu_io_hmul : _alu_io_mac;
  wire        _GEN_0 = i == 2'h0;
  wire        _GEN_1 = j == 2'h0;
  wire        _GEN_2 = _GEN_0 & _GEN_1;
  wire        _GEN_3 = j == 2'h1;
  wire        _GEN_4 = _GEN_0 & _GEN_3;
  wire        _GEN_5 = j == 2'h2;
  wire        _GEN_6 = _GEN_0 & _GEN_5;
  wire        _GEN_7 = _GEN_0 & (&j);
  wire        _GEN_8 = i == 2'h1;
  wire        _GEN_9 = _GEN_8 & _GEN_1;
  wire        _GEN_10 = _GEN_8 & _GEN_3;
  wire        _GEN_11 = _GEN_8 & _GEN_5;
  wire        _GEN_12 = _GEN_8 & (&j);
  wire        _GEN_13 = i == 2'h2;
  wire        _GEN_14 = _GEN_13 & _GEN_1;
  wire        _GEN_15 = _GEN_13 & _GEN_3;
  wire        _GEN_16 = _GEN_13 & _GEN_5;
  wire        _GEN_17 = _GEN_13 & (&j);
  wire        _GEN_18 = (&i) & _GEN_1;
  wire        _GEN_19 = (&i) & _GEN_3;
  wire        _GEN_20 = (&i) & _GEN_5;
  wire        _GEN_21 = (&i) & (&j);
  wire        isElemWalk = op == 4'h4 | op == 4'h5 | op == 4'h6 | _isElemWalk_T_5;
  wire        _GEN_22 = op == 4'h0;
  wire        _GEN_23 = latchedRow == 2'h0;
  wire        _GEN_24 = latchedCol == 2'h0;
  wire        _GEN_25 = _GEN_23 & _GEN_24;
  wire        _GEN_26 = latchedCol == 2'h1;
  wire        _GEN_27 = _GEN_23 & _GEN_26;
  wire        _GEN_28 = latchedCol == 2'h2;
  wire        _GEN_29 = _GEN_23 & _GEN_28;
  wire        _GEN_30 = _GEN_23 & (&latchedCol);
  wire        _GEN_31 = latchedRow == 2'h1;
  wire        _GEN_32 = _GEN_31 & _GEN_24;
  wire        _GEN_33 = _GEN_31 & _GEN_26;
  wire        _GEN_34 = _GEN_31 & _GEN_28;
  wire        _GEN_35 = _GEN_31 & (&latchedCol);
  wire        _GEN_36 = latchedRow == 2'h2;
  wire        _GEN_37 = _GEN_36 & _GEN_24;
  wire        _GEN_38 = _GEN_36 & _GEN_26;
  wire        _GEN_39 = _GEN_36 & _GEN_28;
  wire        _GEN_40 = _GEN_36 & (&latchedCol);
  wire        _GEN_41 = (&latchedRow) & _GEN_24;
  wire        _GEN_42 = (&latchedRow) & _GEN_26;
  wire        _GEN_43 = (&latchedRow) & _GEN_28;
  wire        _GEN_44 = (&latchedRow) & (&latchedCol);
  wire        _GEN_45 = op == 4'h1;
  wire        _GEN_46 = op == 4'h2;
  wire        _GEN_47 = op == 4'hB;
  wire        _GEN_48 = op == 4'h3;
  wire        _GEN_49 = op == 4'h9;
  wire        _GEN_50 = _GEN_46 | _GEN_47;
  wire        _GEN_51 = _GEN_45 | _GEN_50;
  wire        _GEN_52 = op == 4'hA;
  wire        fin = (&j) & (&i);
  wire        _GEN_53 = _GEN_49 | _GEN_52;
  wire        fin_1 = (&j) & (&i);
  wire        _GEN_54 = _GEN_22 | _GEN_45 | _GEN_46 | _GEN_47 | _GEN_48 | _GEN_53;
  always @(posedge clock) begin
    if (reset) begin
      a_0_0 <= 8'h0;
      a_0_1 <= 8'h0;
      a_0_2 <= 8'h0;
      a_0_3 <= 8'h0;
      a_1_0 <= 8'h0;
      a_1_1 <= 8'h0;
      a_1_2 <= 8'h0;
      a_1_3 <= 8'h0;
      a_2_0 <= 8'h0;
      a_2_1 <= 8'h0;
      a_2_2 <= 8'h0;
      a_2_3 <= 8'h0;
      a_3_0 <= 8'h0;
      a_3_1 <= 8'h0;
      a_3_2 <= 8'h0;
      a_3_3 <= 8'h0;
      b_0_0 <= 8'h0;
      b_0_1 <= 8'h0;
      b_0_2 <= 8'h0;
      b_0_3 <= 8'h0;
      b_1_0 <= 8'h0;
      b_1_1 <= 8'h0;
      b_1_2 <= 8'h0;
      b_1_3 <= 8'h0;
      b_2_0 <= 8'h0;
      b_2_1 <= 8'h0;
      b_2_2 <= 8'h0;
      b_2_3 <= 8'h0;
      b_3_0 <= 8'h0;
      b_3_1 <= 8'h0;
      b_3_2 <= 8'h0;
      b_3_3 <= 8'h0;
      c_0_0 <= 32'h0;
      c_0_1 <= 32'h0;
      c_0_2 <= 32'h0;
      c_0_3 <= 32'h0;
      c_1_0 <= 32'h0;
      c_1_1 <= 32'h0;
      c_1_2 <= 32'h0;
      c_1_3 <= 32'h0;
      c_2_0 <= 32'h0;
      c_2_1 <= 32'h0;
      c_2_2 <= 32'h0;
      c_2_3 <= 32'h0;
      c_3_0 <= 32'h0;
      c_3_1 <= 32'h0;
      c_3_2 <= 32'h0;
      c_3_3 <= 32'h0;
      busy <= 1'h0;
      done <= 1'h0;
      rdata <= 32'h0;
      op <= 4'h0;
      i <= 2'h0;
      j <= 2'h0;
      k <= 2'h0;
      latchedRow <= 2'h0;
      latchedCol <= 2'h0;
      latchedData <= 8'h0;
    end
    else begin
      if (busy) begin
        if (_GEN_22) begin
          if (_GEN_25)
            a_0_0 <= latchedData;
          if (_GEN_27)
            a_0_1 <= latchedData;
          if (_GEN_29)
            a_0_2 <= latchedData;
          if (_GEN_30)
            a_0_3 <= latchedData;
          if (_GEN_32)
            a_1_0 <= latchedData;
          if (_GEN_33)
            a_1_1 <= latchedData;
          if (_GEN_34)
            a_1_2 <= latchedData;
          if (_GEN_35)
            a_1_3 <= latchedData;
          if (_GEN_37)
            a_2_0 <= latchedData;
          if (_GEN_38)
            a_2_1 <= latchedData;
          if (_GEN_39)
            a_2_2 <= latchedData;
          if (_GEN_40)
            a_2_3 <= latchedData;
          if (_GEN_41)
            a_3_0 <= latchedData;
          if (_GEN_42)
            a_3_1 <= latchedData;
          if (_GEN_43)
            a_3_2 <= latchedData;
          if (_GEN_44)
            a_3_3 <= latchedData;
        end
        else if (~_GEN_51) begin
          if (_GEN_48) begin
            a_0_0 <= 8'h0;
            a_0_1 <= 8'h0;
            a_0_2 <= 8'h0;
            a_0_3 <= 8'h0;
            a_1_0 <= 8'h0;
            a_1_1 <= 8'h0;
            a_1_2 <= 8'h0;
            a_1_3 <= 8'h0;
            a_2_0 <= 8'h0;
            a_2_1 <= 8'h0;
            a_2_2 <= 8'h0;
            a_2_3 <= 8'h0;
            a_3_0 <= 8'h0;
            a_3_1 <= 8'h0;
            a_3_2 <= 8'h0;
            a_3_3 <= 8'h0;
          end
          else if (_GEN_49) begin
            a_0_0 <= latchedData;
            a_0_1 <= latchedData;
            a_0_2 <= latchedData;
            a_0_3 <= latchedData;
            a_1_0 <= latchedData;
            a_1_1 <= latchedData;
            a_1_2 <= latchedData;
            a_1_3 <= latchedData;
            a_2_0 <= latchedData;
            a_2_1 <= latchedData;
            a_2_2 <= latchedData;
            a_2_3 <= latchedData;
            a_3_0 <= latchedData;
            a_3_1 <= latchedData;
            a_3_2 <= latchedData;
            a_3_3 <= latchedData;
          end
        end
        busy <=
          ~_GEN_54 & (isElemWalk ? ~fin & busy : _alu_io_b_T & ~((&k) & fin_1) & busy);
      end
      else
        busy <= io_start | busy;
      if (~(~busy | _GEN_22)) begin
        if (_GEN_45) begin
          if (_GEN_25)
            b_0_0 <= latchedData;
          if (_GEN_27)
            b_0_1 <= latchedData;
          if (_GEN_29)
            b_0_2 <= latchedData;
          if (_GEN_30)
            b_0_3 <= latchedData;
          if (_GEN_32)
            b_1_0 <= latchedData;
          if (_GEN_33)
            b_1_1 <= latchedData;
          if (_GEN_34)
            b_1_2 <= latchedData;
          if (_GEN_35)
            b_1_3 <= latchedData;
          if (_GEN_37)
            b_2_0 <= latchedData;
          if (_GEN_38)
            b_2_1 <= latchedData;
          if (_GEN_39)
            b_2_2 <= latchedData;
          if (_GEN_40)
            b_2_3 <= latchedData;
          if (_GEN_41)
            b_3_0 <= latchedData;
          if (_GEN_42)
            b_3_1 <= latchedData;
          if (_GEN_43)
            b_3_2 <= latchedData;
          if (_GEN_44)
            b_3_3 <= latchedData;
        end
        else if (~_GEN_50) begin
          if (_GEN_48) begin
            b_0_0 <= 8'h0;
            b_0_1 <= 8'h0;
            b_0_2 <= 8'h0;
            b_0_3 <= 8'h0;
            b_1_0 <= 8'h0;
            b_1_1 <= 8'h0;
            b_1_2 <= 8'h0;
            b_1_3 <= 8'h0;
            b_2_0 <= 8'h0;
            b_2_1 <= 8'h0;
            b_2_2 <= 8'h0;
            b_2_3 <= 8'h0;
            b_3_0 <= 8'h0;
            b_3_1 <= 8'h0;
            b_3_2 <= 8'h0;
            b_3_3 <= 8'h0;
          end
          else if (_GEN_49 | ~_GEN_52) begin
          end
          else begin
            b_0_0 <= latchedData;
            b_0_1 <= latchedData;
            b_0_2 <= latchedData;
            b_0_3 <= latchedData;
            b_1_0 <= latchedData;
            b_1_1 <= latchedData;
            b_1_2 <= latchedData;
            b_1_3 <= latchedData;
            b_2_0 <= latchedData;
            b_2_1 <= latchedData;
            b_2_2 <= latchedData;
            b_2_3 <= latchedData;
            b_3_0 <= latchedData;
            b_3_1 <= latchedData;
            b_3_2 <= latchedData;
            b_3_3 <= latchedData;
          end
        end
      end
      if (~(~busy | _GEN_22 | _GEN_51)) begin
        if (_GEN_48) begin
          c_0_0 <= 32'h0;
          c_0_1 <= 32'h0;
          c_0_2 <= 32'h0;
          c_0_3 <= 32'h0;
          c_1_0 <= 32'h0;
          c_1_1 <= 32'h0;
          c_1_2 <= 32'h0;
          c_1_3 <= 32'h0;
          c_2_0 <= 32'h0;
          c_2_1 <= 32'h0;
          c_2_2 <= 32'h0;
          c_2_3 <= 32'h0;
          c_3_0 <= 32'h0;
          c_3_1 <= 32'h0;
          c_3_2 <= 32'h0;
          c_3_3 <= 32'h0;
        end
        else if (~_GEN_53) begin
          if (isElemWalk) begin
            if (_GEN_2) begin
              if (_elemC_T_6)
                c_0_0 <= _GEN;
              else if (_elemC_T_4)
                c_0_0 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_0_0 <= _alu_io_msub;
              else if (_elemC_T)
                c_0_0 <= _alu_io_madd;
              else
                c_0_0 <= casez_tmp_24;
            end
            if (_GEN_4) begin
              if (_elemC_T_6)
                c_0_1 <= _GEN;
              else if (_elemC_T_4)
                c_0_1 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_0_1 <= _alu_io_msub;
              else if (_elemC_T)
                c_0_1 <= _alu_io_madd;
              else
                c_0_1 <= casez_tmp_24;
            end
            if (_GEN_6) begin
              if (_elemC_T_6)
                c_0_2 <= _GEN;
              else if (_elemC_T_4)
                c_0_2 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_0_2 <= _alu_io_msub;
              else if (_elemC_T)
                c_0_2 <= _alu_io_madd;
              else
                c_0_2 <= casez_tmp_24;
            end
            if (_GEN_7) begin
              if (_elemC_T_6)
                c_0_3 <= _GEN;
              else if (_elemC_T_4)
                c_0_3 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_0_3 <= _alu_io_msub;
              else if (_elemC_T)
                c_0_3 <= _alu_io_madd;
              else
                c_0_3 <= casez_tmp_24;
            end
            if (_GEN_9) begin
              if (_elemC_T_6)
                c_1_0 <= _GEN;
              else if (_elemC_T_4)
                c_1_0 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_1_0 <= _alu_io_msub;
              else if (_elemC_T)
                c_1_0 <= _alu_io_madd;
              else
                c_1_0 <= casez_tmp_24;
            end
            if (_GEN_10) begin
              if (_elemC_T_6)
                c_1_1 <= _GEN;
              else if (_elemC_T_4)
                c_1_1 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_1_1 <= _alu_io_msub;
              else if (_elemC_T)
                c_1_1 <= _alu_io_madd;
              else
                c_1_1 <= casez_tmp_24;
            end
            if (_GEN_11) begin
              if (_elemC_T_6)
                c_1_2 <= _GEN;
              else if (_elemC_T_4)
                c_1_2 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_1_2 <= _alu_io_msub;
              else if (_elemC_T)
                c_1_2 <= _alu_io_madd;
              else
                c_1_2 <= casez_tmp_24;
            end
            if (_GEN_12) begin
              if (_elemC_T_6)
                c_1_3 <= _GEN;
              else if (_elemC_T_4)
                c_1_3 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_1_3 <= _alu_io_msub;
              else if (_elemC_T)
                c_1_3 <= _alu_io_madd;
              else
                c_1_3 <= casez_tmp_24;
            end
            if (_GEN_14) begin
              if (_elemC_T_6)
                c_2_0 <= _GEN;
              else if (_elemC_T_4)
                c_2_0 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_2_0 <= _alu_io_msub;
              else if (_elemC_T)
                c_2_0 <= _alu_io_madd;
              else
                c_2_0 <= casez_tmp_24;
            end
            if (_GEN_15) begin
              if (_elemC_T_6)
                c_2_1 <= _GEN;
              else if (_elemC_T_4)
                c_2_1 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_2_1 <= _alu_io_msub;
              else if (_elemC_T)
                c_2_1 <= _alu_io_madd;
              else
                c_2_1 <= casez_tmp_24;
            end
            if (_GEN_16) begin
              if (_elemC_T_6)
                c_2_2 <= _GEN;
              else if (_elemC_T_4)
                c_2_2 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_2_2 <= _alu_io_msub;
              else if (_elemC_T)
                c_2_2 <= _alu_io_madd;
              else
                c_2_2 <= casez_tmp_24;
            end
            if (_GEN_17) begin
              if (_elemC_T_6)
                c_2_3 <= _GEN;
              else if (_elemC_T_4)
                c_2_3 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_2_3 <= _alu_io_msub;
              else if (_elemC_T)
                c_2_3 <= _alu_io_madd;
              else
                c_2_3 <= casez_tmp_24;
            end
            if (_GEN_18) begin
              if (_elemC_T_6)
                c_3_0 <= _GEN;
              else if (_elemC_T_4)
                c_3_0 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_3_0 <= _alu_io_msub;
              else if (_elemC_T)
                c_3_0 <= _alu_io_madd;
              else
                c_3_0 <= casez_tmp_24;
            end
            if (_GEN_19) begin
              if (_elemC_T_6)
                c_3_1 <= _GEN;
              else if (_elemC_T_4)
                c_3_1 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_3_1 <= _alu_io_msub;
              else if (_elemC_T)
                c_3_1 <= _alu_io_madd;
              else
                c_3_1 <= casez_tmp_24;
            end
            if (_GEN_20) begin
              if (_elemC_T_6)
                c_3_2 <= _GEN;
              else if (_elemC_T_4)
                c_3_2 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_3_2 <= _alu_io_msub;
              else if (_elemC_T)
                c_3_2 <= _alu_io_madd;
              else
                c_3_2 <= casez_tmp_24;
            end
            if (_GEN_21) begin
              if (_elemC_T_6)
                c_3_3 <= _GEN;
              else if (_elemC_T_4)
                c_3_3 <= _alu_io_hmul;
              else if (_elemC_T_2)
                c_3_3 <= _alu_io_msub;
              else if (_elemC_T)
                c_3_3 <= _alu_io_madd;
              else
                c_3_3 <= casez_tmp_24;
            end
          end
          else begin
            if (_alu_io_b_T & _GEN_2)
              c_0_0 <= matmulC;
            if (_alu_io_b_T & _GEN_4)
              c_0_1 <= matmulC;
            if (_alu_io_b_T & _GEN_6)
              c_0_2 <= matmulC;
            if (_alu_io_b_T & _GEN_7)
              c_0_3 <= matmulC;
            if (_alu_io_b_T & _GEN_9)
              c_1_0 <= matmulC;
            if (_alu_io_b_T & _GEN_10)
              c_1_1 <= matmulC;
            if (_alu_io_b_T & _GEN_11)
              c_1_2 <= matmulC;
            if (_alu_io_b_T & _GEN_12)
              c_1_3 <= matmulC;
            if (_alu_io_b_T & _GEN_14)
              c_2_0 <= matmulC;
            if (_alu_io_b_T & _GEN_15)
              c_2_1 <= matmulC;
            if (_alu_io_b_T & _GEN_16)
              c_2_2 <= matmulC;
            if (_alu_io_b_T & _GEN_17)
              c_2_3 <= matmulC;
            if (_alu_io_b_T & _GEN_18)
              c_3_0 <= matmulC;
            if (_alu_io_b_T & _GEN_19)
              c_3_1 <= matmulC;
            if (_alu_io_b_T & _GEN_20)
              c_3_2 <= matmulC;
            if (_alu_io_b_T & _GEN_21)
              c_3_3 <= matmulC;
          end
        end
      end
      done <= busy & (_GEN_54 | (isElemWalk ? fin : ~_alu_io_b_T | (&k) & fin_1));
      if (~(~busy | _GEN_22 | _GEN_45)) begin
        if (_GEN_46)
          rdata <= casez_tmp_29;
        else if (_GEN_47)
          rdata <= {24'h0, casez_tmp_34};
        else if (_GEN_48)
          rdata <= 32'h0;
      end
      if (~busy & io_start) begin
        op <= io_opcode;
        latchedRow <= io_row;
        latchedCol <= io_col;
        latchedData <= io_data;
      end
      if (busy) begin
        if (~_GEN_54) begin
          if (isElemWalk) begin
            if ((&j) & ~(&i))
              i <= i + 2'h1;
            if (&j)
              j <= 2'h0;
            else
              j <= j + 2'h1;
          end
          else begin
            if (_alu_io_b_T & (&k) & (&j) & ~(&i))
              i <= i + 2'h1;
            if (_alu_io_b_T & (&k)) begin
              if (&j)
                j <= 2'h0;
              else
                j <= j + 2'h1;
            end
          end
        end
        if (_GEN_22 | _GEN_45 | _GEN_46 | _GEN_47 | _GEN_48 | _GEN_49 | _GEN_52
            | isElemWalk | ~_alu_io_b_T) begin
        end
        else if (&k)
          k <= 2'h0;
        else
          k <= k + 2'h1;
      end
      else if (io_start) begin
        i <= 2'h0;
        j <= 2'h0;
        k <= 2'h0;
      end
    end
  end // always @(posedge)
  MatrixAlu alu (
    .io_a    (_alu_io_a_T_3),
    .io_b    (_alu_io_b_T ? casez_tmp_14 : casez_tmp_19),
    .io_c    (casez_tmp_24),
    .io_madd (_alu_io_madd),
    .io_msub (_alu_io_msub),
    .io_hmul (_alu_io_hmul),
    .io_mac  (_alu_io_mac)
  );
  assign io_rdata = rdata;
  assign io_done = done;
  assign io_busy = busy;
endmodule

module FrameMatrix #(
  parameter int IO_WIDTH = 66
) (
  input                  clock,
                         reset,
  input  [IO_WIDTH-1:0]  io_in,
  output [IO_WIDTH-1:0]  io_out,
                         io_oe
);

  wire [31:0] _core_io_rdata;
  wire        _core_io_done;
  wire        _core_io_busy;
  MatrixCore core (
    .clock     (clock),
    .reset     (reset),
    .io_opcode (io_in[15:12]),
    .io_row    (io_in[9:8]),
    .io_col    (io_in[11:10]),
    .io_data   (io_in[7:0]),
    .io_start  (io_in[16]),
    .io_rdata  (_core_io_rdata),
    .io_done   (_core_io_done),
    .io_busy   (_core_io_busy)
  );
  assign io_out = {15'h0, _core_io_busy, _core_io_done, _core_io_rdata, 17'h0};
  assign io_oe = 66'h7FFFFFFFE0000;
endmodule

